### PR TITLE
APIs for Topics and Categories

### LINKED ISSUE #3: Writing the APIs for data on landing page using GraphQL
Working on it.

### PR DESCRIPTION
**Pull request by DevanshCodes**
These APIs are written keeping the current front end in the mind, will add more fields in the Schema, these are currently fetching the data which the current front end demands.

### CODE REVIEW

**Comment by DevanshCodes** [comment]
@jaskirat2000 @vaibhavdaren @devesh-verma

**Comment by jaskiratsingh2000** [comment]
I am leaving this on @devesh-verma to look

**Comment by DevanshCodes** [comment]
Humble Reminder for PR, @devesh-verma @jaskiratsingh2000 @vaibhavdaren ,
Thanks!

**Comment by devesh-verma** [comment]
@DevanshCodes Remember to add new line at the end of every file. Use a linter.

**Comment by DevanshCodes** [comment]
> @DevanshCodes Remember to add new line at the end of every file. Use a linter.

Yes, I use PrettierJS though for formatting.

**Pull request merged**
